web:
    image: nginx:latest
    ports:
        - "8080:80"
    volumes:
        - ./code:/code
        - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
        - php
php:
    build: .
    volumes:
        - ./code:/code
    links:
        - mysql
mysql:
    image: mysql:5.7
    ports: 
        - "3307:3306"
    environment:
        MYSQL_DATABASE: drupal
        MYSQL_USER: drupal 
        MYSQL_PASSWORD: password 
        MYSQL_ROOT_PASSWORD: password
    volumes:
        - ./mysqldata:/var/lib/mysql/

    